rev1_case_v1_pattern.dxf : rev1_case_v1_pattern.scad rev1_case_v1.scad \
		rev1_case_v1_dimensions.scad rev1_dimensions.scad rev1.scad
	/home/kms15private/git/openscad/openscad $< -o $@

clean:
	rm -f rev1_case_v1_pattern.dxf
